package com.xnihilfx.sirmobile.ui.theme

import androidx.compose.ui.graphics.Color

// Paleta SIR — teal claro, Material 3 COMPLETO (todos los roles definidos para
// que no se filtre el morado/lavanda por defecto de Material 3).

// ---- Light ----
val LightPrimary = Color(0xFF136D66)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFA6F2E9)
val LightOnPrimaryContainer = Color(0xFF00201D)
val LightSecondary = Color(0xFF4B6360)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCDE8E3)
val LightOnSecondaryContainer = Color(0xFF05201D)
val LightTertiary = Color(0xFF156A7C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFBDEAF7)
val LightOnTertiaryContainer = Color(0xFF001F28)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF4FBF9)
val LightOnBackground = Color(0xFF161D1C)
val LightSurface = Color(0xFFF4FBF9)
val LightOnSurface = Color(0xFF161D1C)
val LightSurfaceVariant = Color(0xFFDAE5E1)
val LightOnSurfaceVariant = Color(0xFF3F4946)
val LightOutline = Color(0xFF6F7977)
val LightOutlineVariant = Color(0xFFBEC9C5)
val LightInverseSurface = Color(0xFF2B3231)
val LightInverseOnSurface = Color(0xFFECF2EF)
val LightInversePrimary = Color(0xFF8AD6CC)
val LightSurfaceTint = LightPrimary
val LightSurfaceDim = Color(0xFFD5DBD9)
val LightSurfaceBright = Color(0xFFF4FBF9)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFEFF5F2)
val LightSurfaceContainer = Color(0xFFE9EFED)
val LightSurfaceContainerHigh = Color(0xFFE3EAE7)
val LightSurfaceContainerHighest = Color(0xFFDDE4E1)

// ---- Dark ----
val DarkPrimary = Color(0xFF89D5CB)
val DarkOnPrimary = Color(0xFF00382F)
val DarkPrimaryContainer = Color(0xFF00504A)
val DarkOnPrimaryContainer = Color(0xFFA6F2E9)
val DarkSecondary = Color(0xFFB1CCC6)
val DarkOnSecondary = Color(0xFF1C3531)
val DarkSecondaryContainer = Color(0xFF334B47)
val DarkOnSecondaryContainer = Color(0xFFCDE8E3)
val DarkTertiary = Color(0xFFA1CEE0)
val DarkOnTertiary = Color(0xFF003543)
val DarkTertiaryContainer = Color(0xFF1E4E5B)
val DarkOnTertiaryContainer = Color(0xFFBDEAF7)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF0E1514)
val DarkOnBackground = Color(0xFFDEE4E2)
val DarkSurface = Color(0xFF0E1514)
val DarkOnSurface = Color(0xFFDEE4E2)
val DarkSurfaceVariant = Color(0xFF3F4946)
val DarkOnSurfaceVariant = Color(0xFFBEC9C5)
val DarkOutline = Color(0xFF899390)
val DarkOutlineVariant = Color(0xFF3F4946)
val DarkInverseSurface = Color(0xFFDEE4E2)
val DarkInverseOnSurface = Color(0xFF2B3231)
val DarkInversePrimary = Color(0xFF136D66)
val DarkSurfaceTint = DarkPrimary
val DarkSurfaceDim = Color(0xFF0E1514)
val DarkSurfaceBright = Color(0xFF343A39)
val DarkSurfaceContainerLowest = Color(0xFF090F0E)
val DarkSurfaceContainerLow = Color(0xFF161D1C)
val DarkSurfaceContainer = Color(0xFF1A2120)
val DarkSurfaceContainerHigh = Color(0xFF252B2A)
val DarkSurfaceContainerHighest = Color(0xFF2F3635)
